
export const Data =
{
    project : [
        {
            "projectAM": "Sadla",
            "customers": "ReNew Power",
            "turbines": "SDLT01_WTUR",
            "selectalarmbuttonAM": "Custom",
            "fromdateAM": "9-Sep-2022",
            "todateAM": "9-Sep-2022",
            "EnterValueInGrid1": "04:Operational:WTG_OK",
            "EnterValueInGrid2": "08:Non Operational:BD",
            "EnterValueInGrid3": "12:Operational:EG",
            "EnterValueInGrid4": "16:Non Operational:IG",
            "EnterValueInGrid5": "20:Operational:WTG_OK",
            "EnterValueInGrid6": "2359:Non Operational:EG",
            "projecttrends": "Stg-Porbandar Solar",
            "fromdatetrends": "7-Sep-2022",
            "todatetrends": "7-Sep-2022",
            "selectalarmbuttontrends": "Custom",
            "navigatetomenutree": "Inverter:1A",
            "draganddropelements-1": "AC Frequency",
            "draganddropelements-2": "PV Voltage",
            "draganddropelements-3": "AC Voltage V23",
            "draganddropelements-4": "AC Voltage V31",
            "draganddropelements-5": "Active Power",
            "draganddropelements-6": "Apparent Power",
            "displaychart": "View data table"
        },
        {
            "projectAM": "Jaora",
            "customers": "Continum",
            "turbines": "DJE01_WTUR",
            "selectalarmbuttonAM": "Custom",
            "fromdateAM": "7-Sep-2022",
            "todateAM": "7-Sep-2022",
            "EnterValueInGrid1": "04:Operational:WTG_OK",
            "EnterValueInGrid2": "08:Non Operational:EG",
            "EnterValueInGrid3": "12:Operational:EG",
            "EnterValueInGrid4": "16:Non Operational:IG",
            "EnterValueInGrid5": "20:Operational:WTG_OK",
            "EnterValueInGrid6": "2359:Non Operational:EG",
            "projecttrends": "Stg-JAORA",
            "fromdatetrends": "7-Sep-2022",
            "todatetrends": "7-Sep-2022",
            "selectalarmbuttontrends": "Custom",
            "navigatetomenutree": "Turbine:DJE01:General",
            "draganddropelements-1": "Active Power",
            "draganddropelements-2": "Reactive power",
            "draganddropelements-3": "Turbine status",
            "draganddropelements-4": "Turbine Time UTC",
            "draganddropelements-5": "Turbine Time Local",
            "draganddropelements-6": "Auto Quit Level",
            "displaychart": "View data table"
        },
        {
            "projectAM": "Brisa Portiguar Group 1",
            "customers": "ASA Branca 1",
            "turbines": "AB101_WTUR",
            "selectalarmbuttonAM": "Custom",
            "fromdateAM": "9-Sep-2022",
            "todateAM": "9-Sep-2022",
            "EnterValueInGrid1": "04:Operational:IAONGEL",
            "EnterValueInGrid2": "08:Non Operational:IANOFO",
            "EnterValueInGrid3": "12:Operational:IAONGEN",
            "EnterValueInGrid4": "16:Non Operational:IANOPCA",
            "EnterValueInGrid5": "20:Operational:IAOGPP",
            "EnterValueInGrid6": "2359:Non Operational:IANOSM",
            "projecttrends": "Stg-Brisa Portiguar Group 1",
            "fromdatetrends": "9-Sep-2022",
            "todatetrends": "9-Sep-2022",
            "selectalarmbuttontrends": "Custom",
            "navigatetomenutree": "Turbine:AB101:General",
            "draganddropelements-1": "Active power",
            "draganddropelements-2": "Reactive power",
            "draganddropelements-3": "Turbine status",
            "draganddropelements-4": "Wind-Direction",
            "draganddropelements-5": "Wind-Speed",
            "draganddropelements-6": "Auto Quit Level",
            "displaychart": "View data table"
        },
        {
            "projectAM": "Brisa Portiguar Group 2",
            "customers": "SANTA HELENA",
            "turbines": "SH10_WTUR",
            "selectalarmbuttonAM": "Custom",
            "fromdateAM": "9-Sep-2022",
            "todateAM": "9-Sep-2022",
            "EnterValueInGrid1": "04:Operational:IAONGEL",
            "EnterValueInGrid2": "08:Non Operational:IANOFO",
            "EnterValueInGrid3": "12:Operational:IAONGEN",
            "EnterValueInGrid4": "16:Non Operational:IANOPCA",
            "EnterValueInGrid5": "20:Operational:IAOGPP",
            "EnterValueInGrid6": "2359:Non Operational:IANOSM",
            "projecttrends": "Stg-Brisa Portiguar Group 2",
            "fromdatetrends": "9-Sep-2022",
            "todatetrends": "9-Sep-2022",
            "selectalarmbuttontrends": "Custom",
            "navigatetomenutree": "Turbine:SH01:General",
            "draganddropelements-1": "Active power",
            "draganddropelements-2": "Reactive power",
            "draganddropelements-3": "Turbine status",
            "draganddropelements-4": "Wind-Direction",
            "draganddropelements-5": "Wind-Speed",
            "draganddropelements-6": "Auto Quit Level",
            "displaychart": "View data table"
        },
        {
            "projectAM": "Rajkot",
            "customers": "Powerica",
            "turbines": "AMB01_WTUR",
            "selectalarmbuttonAM": "Custom",
            "fromdateAM": "14-Sep-2022",
            "todateAM": "14-Sep-2022",
            "EnterValueInGrid1": "04:Non Operational:Faulted",
            "EnterValueInGrid2": "08:Operational:WTG_OK",
            "EnterValueInGrid3": "12:Non Operational:Faulted",
            "EnterValueInGrid4": "1659:Operational:WTG_OK",
            "EnterValueInGrid5": "20:Operational:WTG_OK",
            "EnterValueInGrid6": "2359:Non Operational:Faulted",
            "projecttrends": "Stg-Rajkot",
            "fromdatetrends": "12-Sep-2022",
            "todatetrends": "12-Sep-2022",
            "selectalarmbuttontrends": "Custom",
            "navigatetomenutree": "Turbine:AMB01:General",
            "draganddropelements-1": "Active power",
            "draganddropelements-2": "Reactive power",
            "draganddropelements-3": "Turbine status",
            "draganddropelements-4": "Generation today",
            "draganddropelements-5": "Total Generation",
            "draganddropelements-6": "PLF",
            "displaychart": "View data table"
        }
    ]
}