export const JMRData =
// {
// JMR: [
{
    "AddButton": "add",

    // "AddProject": "Demo Project",
    "AddProject": "DMRC Aerocity Metro Station",

    "BillingDateButton": "Billing Month",
    "BillingDate": "30-Dec-2022",
    "ScheduleStartButton": "Schedule Start",
    "ScheduleEndButton": "Schedule End",
    "ScheduledStartDate": "25-Jan-2023",
    "ScheduledEndDate": "26-Jan-2023",
    "JMRStartDate": "25-Jan-2023",
    "JMREndDate": "26-Jan-2023",
    "AssignedToSearchButton": "Assigned To",
    "ApproverSearchButton": "Approver",
    "AddAssignedToUser1": "Prahlad Prajapati",
    "AddAssignedToUser2": "Anupama P P",
    "AddAssignedToUser3": "Atchaya C",
    "AddApproverUser1": "Rushikesh Tayade",
    "AddApproverUser2": "Rushikesh Tayade",
    "AddApproverUser3": "Abhilasha",
    "AssetsName": "Name",
    // "AssetsName_Value-1": "Asset1",
    // "AssetsName_Value-2": "Asset2",
    // "AssetsName_Value-3": "Asset 3",
    // "AssetsName_Value-4": "Demo Asset",

    "AssetsName_Value-1": "inv_01_String 1",
    "AssetsName_Value-2": "inv_01_String 2",
    "AssetsName_Value-3": "inv_01_String 3",
    "AssetsName_Value-4": "inv_01_String 4",

    "AssetsCode": "Code",

    // "AssetsCode_Value-1": "IN.PRES.DEMO.AA9176B",
    // "AssetsCode_Value-2": "IN.PRES.DEMO.AA9176B",
    // "AssetsCode_Value-3": "IN.PRES.DEMO.AA9176B",
    // "AssetsCode_Value-4": "IN.PRES.DEMO.AA9176B",

    "AssetsCode_Value-1": "IN.RADI.ACMS.AB1349M",
    "AssetsCode_Value-2": "IN.RADI.ACMS.AB1349N",
    "AssetsCode_Value-3": "IN.RADI.ACMS.AB1349O",
    "AssetsCode_Value-4": "IN.RADI.ACMS.AB1349P",
    "AssetSearch": "Search",
    "AssetReset": "Reset",
    "BilldUnit-1": "123.12",
    "BilldUnit-2": "456.52",
    "BilldUnit-3": "789.77",
    "BilldUnit-4": "852.16",
    "DeemedGeneration-1": "321.52",
    "DeemedGeneration-2": "654.25",
    "DeemedGeneration-3": "987.61",
    "DeemedGeneration-4": "258.07",
    "SaveButton": "save",
    "PopUpYes": "Yes",
    "PopUpOk": " Ok",
    "FilterSPVName": "SPV Name",
    "SPVName-1": "123Demo",
    "FilterLocation": "Location",
    "Location-1": "Bengaluru",
    "FilterProject": "Project",
    "Project-1": "Demo Project",
    "FilterBillingMonthBtn": "Search",
    "BulkUpdateBillingMonthBtn": "Update",
    "BillingMonthBtn1": "Billing Month",
    // "BillingDate": "9-Sep-2022",
    "Status": "Status",
    "StatusValue1": "Work not started",
    "Autorenew": " autorenew ",
    "Refresh": "refresh",
    "SelectJMRForEdit-1": "123Demo",
    "ViewButton": "visibility",
    "EditButton": "edit",
    "EditApproverSearchButton" : "Approver",
    "EditApproverUser1": "Abhilasha",
    "DeleteButton": "delete",
    "DownloadButton": "get_app",
    "BulkUpdateJMRCode-1": "JMRB.AA0011U",
    "BulkUpdateJMRCode-2": "JMRB.AA0011V",
    "BulkUpdateJMRCode-3": "JMRB.AA0011W",
    "BulkUpdateJMRCode-4": "JMRB.AA0011X",
    "BulkUpdateJMRCode-5": "JMRB.AA0011Z",
    "BulkUpdateButton": "Bulk Update",
    "ReadingType": "Reading Type",
    "ReadingTypeValue-1": "Billable",
    "BulkUpdateAssignedToUser1": "Atchaya C",
    "BulkUpdateAssignedToUser2": "Rushikesh Tayade",
    "Remark": "Demo_JMR",
}

    // ]
// }