export const Data =
{
    envorments: [
        {
            "env": "http://20.204.28.204/qav3/login",
            "id": "csm.stride@prescinto.air",
            "pass": "GrowPrescinto@10x",
            "project": "Project",
            "plant": "Hiraco",
            "nevigatetomenu": "Inverter (22):1B",
            "drag&dropelement1": "PV Voltage",
            "drag&dropelement2": "AC Frequency",
            "drag&dropelement3": "AC Voltage V23",
            "drag&dropelement4": "AC Voltage V31",
            "drag&dropelement5": "Active Power",
            "drag&dropelement6": "Apparent Power",
        },

        {
            "env": "http://20.204.28.204/qav3/",
            "id": "csm.radiancerenewables@prescinto.ai",
            "pass": "GrowPrescinto@10x",
            "project": "Project",
            "plant": "Hiraco",
            "nevigatetomenu": "Inverter (22):1B",
            "drag&dropelement1": "PV Voltage",
            "drag&dropelement2": "AC Frequency",
            "drag&dropelement3": "AC Voltage V23",
            "drag&dropelement4": "AC Voltage V31",
            "drag&dropelement5": "Active Power",
            "drag&dropelement6": "Apparent Power",
        },

        {
            "env": "http://20.204.28.204/qav3/",
            "id": "rushikesh.sunil@prescinto.ai",
            "pass": "Rushi000@",
            "project": "Project",
            "plant": "Hiraco",
            "nevigatetomenu": "Inverter (22):1B",
            "drag&dropelement1": "PV Voltage",
            "drag&dropelement2": "AC Frequency",
            "drag&dropelement3": "AC Voltage V23",
            "drag&dropelement4": "AC Voltage V31",
            "drag&dropelement5": "Active Power",
            "drag&dropelement6": "Apparent Power",
        },

        {
            "env": "https://staging.prescinto.ai/v3/login",
            "id": "csm.stride@prescinto.air",
            "pass": "GrowPrescinto@10x",
            "project": "Project",
            "plant": "Hiraco",
            "nevigatetomenu": "Inverter (22):1B",
            "drag&dropelement1": "PV Voltage",
            "drag&dropelement2": "AC Frequency",
            "drag&dropelement3": "AC Voltage V23",
            "drag&dropelement4": "AC Voltage V31",
            "drag&dropelement5": "Active Power",
            "drag&dropelement6": "Apparent Power",
        },

        {
            "env": "https://staging.prescinto.ai/v3/login",
            "id": "csm.radiancerenewables@prescinto.ai",
            "pass": "GrowPrescinto@10x",
            "project": "Project",
            "plant": "Hiraco",
            "nevigatetomenu": "Inverter (22):1B",
            "drag&dropelement1": "PV Voltage",
            "drag&dropelement2": "AC Frequency",
            "drag&dropelement3": "AC Voltage V23",
            "drag&dropelement4": "AC Voltage V31",
            "drag&dropelement5": "Active Power",
            "drag&dropelement6": "Apparent Power",
        },

        {
            "env": "https://staging.prescinto.ai/v3/login",
            "id": "rushikesh.sunil@prescinto.ai",
            "pass": "Rushi000@",
            "project": "Project",
            "plant": "Hiraco",
            "nevigatetomenu": "Inverter (22):1B",
            "drag&dropelement1": "PV Voltage",
            "drag&dropelement2": "AC Frequency",
            "drag&dropelement3": "AC Voltage V23",
            "drag&dropelement4": "AC Voltage V31",
            "drag&dropelement5": "Active Power",
            "drag&dropelement6": "Apparent Power",
        },

        {
            "env": "https://cloud.prescinto.ai/v3/login",
            "id": "csm.stride@prescinto.air",
            "pass": "GrowPrescinto@10x",
            "project": "Project",
            "plant": "Hiraco",
            "nevigatetomenu": "Inverter (22):1B",
            "drag&dropelement1": "PV Voltage",
            "drag&dropelement2": "AC Frequency",
            "drag&dropelement3": "AC Voltage V23",
            "drag&dropelement4": "AC Voltage V31",
            "drag&dropelement5": "Active Power",
            "drag&dropelement6": "Apparent Power",
        },

        {
            "env": "https://cloud.prescinto.ai/v3/login",
            "id": "csm.radiancerenewables@prescinto.ai",
            "pass": "GrowPrescinto@10x",
            "project": "Project",
            "plant": "Hiraco",
            "nevigatetomenu": "Inverter (22):1B",
            "drag&dropelement1": "PV Voltage",
            "drag&dropelement2": "AC Frequency",
            "drag&dropelement3": "AC Voltage V23",
            "drag&dropelement4": "AC Voltage V31",
            "drag&dropelement5": "Active Power",
            "drag&dropelement6": "Apparent Power",
        },
         
        {
            "env": "https://cloud.prescinto.ai/v3/login",
            "id": "rushikesh.sunil@prescinto.ai",
            "pass": "Rushi000@",
            "project": "Project",
            "plant": "Hiraco",
            "nevigatetomenu": "Inverter (22):1B",
            "drag&dropelement1": "PV Voltage",
            "drag&dropelement2": "AC Frequency",
            "drag&dropelement3": "AC Voltage V23",
            "drag&dropelement4": "AC Voltage V31",
            "drag&dropelement5": "Active Power",
            "drag&dropelement6": "Apparent Power",
        },
    ]
}