export const JMRData =
// {
// JMR: [
{
    "AddButton": "add",
    "AddProject": "Demo Project",
    "BillingDateButton": "Billing Month",
    "BillingDate": "9-Sep-2022",
    "ScheduleStartButton": "Schedule Start",
    "ScheduleEndButton": "Schedule End",
    "ScheduledStartDate": "25-Jan-2023",
    "ScheduledEndDate": "26-Jan-2023",
    "JMRStartDate": "25-Jan-2023",
    "JMREndDate": "26-Jan-2023",
    "AssignedToSearchButton": "Assigned To",
    "ApproverSearchButton": "Approver",
    "AddAssignedToUser1": "Atchaya C",
    "AddAssignedToUser2": "Atchaya C",
    "AddAssignedToUser3": "Atchaya C",
    "AddApproverUser1": "Rushikesh Tayade",
    "AddApproverUser2": "Rushikesh Tayade",
    "AddApproverUser3": "Abhilasha",
    "AssetsName": "Name",
    "AssetsName_Value-1": "Inverter 1 (Demo Site)",
    "AssetsName_Value-2": "Inverter 2 (Demo Site)_test",
    "AssetsName_Value-3": "Inverter 3 (Demo Site)",
    "AssetsName_Value-4": "Inverter 4 (Demo Site)",
    "AssetsCode": "Code",
    "AssetsCode_Value-1": "IN.PRES.DEMO.AA1030L",
    "AssetsCode_Value-2": "IN.PRES.DEMO.AA1030M",
    "AssetsCode_Value-3": "IN.PRES.DEMO.AA9176B",
    "AssetsCode_Value-4": "IN.PRES.DEMO.AA9176B",
    "AssetSearch": "Search",
    "AssetReset": "Reset",
    "BilldUnit-1": "123",
    "BilldUnit-2": "456",
    "BilldUnit-3": "789",
    "BilldUnit-4": "852",
    "DeemedGeneration-1": "321",
    "DeemedGeneration-2": "654",
    "DeemedGeneration-3": "987",
    "DeemedGeneration-4": "258",
    "SaveButton": "save",
    "PopUpYes": "Yes",
    "PopUpOk": " Ok",
    "FilterSPVName": "SPV Name",
    "SPVName-1": "123Demo",
    "FilterLocation": "Location",
    "Location-1": "Bengaluru",
    "FilterProject": "Project",
    "Project-1": "Demo Project",
    "FilterBillingMonthBtn": "Search",
    "BulkUpdateBillingMonthBtn": "Update",
    "BillingMonthBtn1": "Billing Month",
    // "BillingDate": "9-Sep-2022",
    "Status": "Status",
    "StatusValue1": "Work not started",
    "Autorenew": " autorenew ",
    "Refresh": "refresh",
    "SelectJMRForEdit-1": "123Demo",
    "ViewButton": "visibility",
    "EditButton": "edit",
    "EditApproverSearchButton" : "Approver",
    "EditApproverUser1": "Abhilasha",
    "DeleteButton": "delete",
    "DownloadButton": "get_app",
    "BulkUpdateJMRCode-1": "JMRB.AA0012O",
    "BulkUpdateJMRCode-2": "JMRB.AA0012P",
    "BulkUpdateJMRCode-3": "JMRB.AA0012Q",
    "BulkUpdateJMRCode-4": "JMRB.AA0012R",
    "BulkUpdateJMRCode-5": "JMRB.AA0012T",
    "BulkUpdateButton": "Bulk Update",
    "ReadingType": "Reading Type",
    "ReadingTypeValue-1": "Billable",
    "BulkUpdateAssignedToUser1": "Atchaya C",
    "BulkUpdateAssignedToUser2": "Rushikesh Tayade",
    "Remark": "Demo_JMR",
}

    // ]
// }