export const workData =
{
  workorder: [
    {

      "Project": "Demo Project",
      "CycleName": "Automation Demo",
      "CycleDetails": "This is a demo module cleaning Cycle",
      "ScheduledStartDate": "23-Feb-2023",
      "ScheduledEndDate": "23-Feb-2023",
      "AssignedTo": "Anupama P P",
      "Approver": "Anupama P P",
      "Crew1": "Prescinto-1",
      "rowindex": "0",
      "AssetName": "INV-06",
      "AssetCode": "IN.PRES.DEMO.AA9717J",
      "Plannedmodules": "2000",
      "planned_date": "23-Feb-2023",
      "CheckModuleCleaningCycle": "Automation Demo",
      "EditScheduledStartDate": "24-Feb-2023",
      "EditScheduledEndDate": "24-Feb-2023",
      "EditCyclePlanDetailsName": "Inverter 1 (Demo Site)",
      "EditCycleDetailsCode": "IN.PRES.DEMO.AA1030L",
      "Editplanned_date": "24-Feb-2023",
      "EditAssignedTo": "Anupama P P",
      "EditApprover": "Anupama P P",
      "EditCrew": "Prescinto-1",
      "DuplicateCycleName": "DuplicateGrass Cutting Demo",
      "DuplicateCycleDetails": "DuplicateDemo grass cutting 2023",
      "DuplicateProject": "Demo Project",
      "DuplicateScheduledStartDate": "25-Feb-2023",
      "DuplicateScheduledEndDate": "25-Feb-2023",
      "DuplicateAssignedTo": "Abhilasha",
      "DuplicateApprover": "Atchaya C",
      "DuplicateCrew": "Prescinto-1",
      "DuplicateAssetName": "INV-06",
      "DuplicateAssetCode": "IN.PRES.DEMO.AA9717J",
      "Duplicateplanned_date": "25-Feb-2023",
      "Year": "25-Feb-2022",
      "FindParticularWorkorder": "MC - All modules cleaning - INV-06",
      "State": "Work not started",
      "FilterCrew": "Prescinto-1",
      "filterAssigneeApprover": "Abhilasha",
      "ClickOnWorkorder": "MC",
      "ChangeState1": "In Progress",
      "AddWaterConsumption": "4",
      "AddCleaningMW": "4",
      "AddReason": "Labour Leave",
      "ClickAndAddButton": "Files",
      "RescheduledAssignedTo": "Anupama P P",
      "RescheduledApprover": "Anupama P P",
      "ChangeState2": "Completed",
      "ClickonRescheduleDate": "Reschedule Start Date",
      "RescheduledStartDate": "25-Feb-2023",
      "RescheduledEndDate": "25-Feb-2023",
      "ChangeTaskStatus": "Completed",
      "Addcleanednoofmodule1": "100",
      "Addcleanednoofmodule2": "2000",
      "Addcleanednoofmodule3": "2"

    }
  ]
}