export const workData =
{
    workorder: [
        {
            "Project":"Demo Project",
            "Classification":"Administrative Task",
            "Activity":"Authentication",
            "ScheduledStart":"12-Nov-2022",
           "ScheduledEnd":"14-Nov-2022",
           "Priority":"High",
           "Warehouse":"Warehouse Demo Test(Internal)",
           "AssignedtoUser":"Atchaya C",
      "ApproverUser":"Atchaya C",
      "Remarks":"High Priority work",
      "ResourceCode":"120000",
      "State":"Work not started",
      "Crew":"deMO CREW",
      "ClickOnWorkorder":"IN.PRES.DEMO.AT.AC7228B",
      "EditScheduledStart":"21-Nov-2022",
      "EditScheduledEnd":"22-Nov-2022",
      },
        {
            "Project":"Demo Project",
            "Classification":"Corrective Maintenance",
            "Subclassification":"Inverters",
            "Activity":"Maintenance Work",
            "ScheduledStart":"12-Nov-2022",
           "ScheduledEnd":"14-Nov-2022",
           "BreakdownStartDate":"10-Nov-2022",
           "BreakdownEndDate":"14-Nov-2022",
           "EventType":"Curtailment",
           "EventBreakdownPercentage":"40",
           "ControllableDCVoltage":"200",
            "Priority":"Low",
            "Warehouse":"Warehouse Demo Test(Internal)",
            "AssignedtoUser":"Atchaya C",
       "ApproverUser":"Atchaya C",
        "Anomaly":"Anomaly Demo Inverters",
        "Addcrew":"deMO CREW",
        "Technician1":"Abhilasha",
        "Technician2":"Abhishek",
        "Remarks":"Do work",
        "ResourceCode":"120000",
        "State":"Work not started",
        "Crew":"deMO CREW",
        "ClickOnWorkorder":"IN.PRES.DEMO.AT.AC7228B",
        "EditScheduledStart":"21-Nov-2022",
        "EditScheduledEnd":"22-Nov-2022",
        },
        {
            "Project":"Demo Project",
            "Classification":"Material Out",
            "Activity":"Material Out",
            "ScheduledStart":"16-Nov-2022",
           "ScheduledEnd":"17-Nov-2022",
           "Priority":"Low",
           "Warehouse":"Warehouse Demo Test(Internal)",
           "AssignedtoUser":"Atchaya C",
      "ApproverUser":"Atchaya C",
      "Remarks":"Do work",
      "ResourceCode":"120000",
      "State":"Work not started",
      "Crew":"deMO CREW",
      "ClickOnWorkorder":"IN.PRES.DEMO.AT.AC7228B",
      "EditScheduledStart":"21-Nov-2022",
      "EditScheduledEnd":"22-Nov-2022",
      },
      {
        "Project":"Demo Project",
        "Classification":"Material Receipt",
        "Activity":"Material Receipt",
        "ScheduledStart":"18-Nov-2022",
       "ScheduledEnd":"19-Nov-2022",
       "Priority":"Low",
       "Warehouse":"Warehouse Demo Test(Internal)",
       "AssignedtoUser":"Atchaya C",
  "ApproverUser":"Atchaya C",
  "Remarks":"Do work",
  "ResourceCode":"120000",
  "State":"Work not started",
  "Crew":"deMO CREW",
  "ClickOnWorkorder":"IN.PRES.DEMO.AT.AC7228B",
  "EditScheduledStart":"21-Nov-2022",
  "EditScheduledEnd":"22-Nov-2022",
  },
  {
    "Project":"Demo Project",
    "Classification":"Miscellaneouse Works",
    "Activity":"Miscellaneouse Works",
    "ScheduledStart":"20-Nov-2022",
   "ScheduledEnd":"21-Nov-2022",
   "Priority":"Low",
   "Warehouse":"Warehouse Demo Test(Internal)",
   "AssignedtoUser":"Atchaya C",
"ApproverUser":"Atchaya C",
"Remarks":"Do work",
"ResourceCode":"120000",
"State":"Work not started",
"Crew":"deMO CREW",
"ClickOnWorkorder":"IN.PRES.DEMO.AT.AC7228B",
"EditScheduledStart":"21-Nov-2022",
"EditScheduledEnd":"22-Nov-2022",
},
{
    "Project":"Demo Project",
    "Classification":"Preventive Maintenance",
    "Subclassification":"Inverters",
    "Activity":"Preventive Demo Test",
    "ScheduledStart":"22-Nov-2022",
   "ScheduledEnd":"23-Nov-2022",
   "BreakdownStartDate":"20-Nov-2022",
   "BreakdownEndDate":"22-Nov-2022",
    "Priority":"Low",
    "Warehouse":"Warehouse Demo Test(Internal)",
    "AssignedtoUser":"Atchaya C",
"ApproverUser":"Atchaya C",
"Anomaly":"Anomaly Demo Inverters",
"Addcrew":"deMO CREW",
"Technician1":"Abhilasha",
"Technician2":"Abhishek",
"Remarks":"Do work",
"ResourceCode":"120000",
"State":"Work not started",
"Crew":"deMO CREW",
"ClickOnWorkorder":"IN.PRES.DEMO.AT.AC7228B",
"EditScheduledStart":"21-Nov-2022",
"EditScheduledEnd":"22-Nov-2022",
},
{
    "Project":"Demo Project",
    "Classification":"Purchase Request",
    "Activity":"Purchase Battery",
    "ScheduledStart":"1-Nov-2022",
   "ScheduledEnd":"4-Nov-2022",
   "Priority":"Low",
   "Warehouse":"Warehouse Demo Test(Internal)",
   "AssignedtoUser":"Atchaya C",
"ApproverUser":"Atchaya C",
"Remarks":"Do work",
"ResourceCode":"120000",
"State":"Work not started",
"Crew":"deMO CREW",
"ClickOnWorkorder":"IN.PRES.DEMO.AT.AC7228B",
"EditScheduledStart":"21-Nov-2022",
"EditScheduledEnd":"22-Nov-2022",
}
    ]
}